name: hydra
description: Flutter widget which helps building responsive widgets.
version: 0.1.0
homepage: https://github.com/igoriuz/hydra
issue_tracker: https://github.com/igoriuz/hydra/issues
repository: https://github.com/igoriuz/hydra

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:

# following page: https://dart.dev/tools/pub/pubspec